# Site settings
title: tFada
email: sebastien.mouret@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog perso, sur l'actualité iTech, le monde Apple, le sport,
  la photo et tout un tas d'autres geekeries. Mes retours sur des produits et
  mes coups de gueules, tout ça dans la bonne humeur. Une partie du site est dédié
  à mon travail de développeur Web fullstack.
baseurl: "/my-awesome-site" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: isebmo
github_username:  isebmo

# Build settings
markdown: kramdown

exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
  tweets:
    output: true
    permalink: /tweets/:path/