# Site settings
title: tFada
email: sebastien.mouret@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog perso, sur l'actualité iTech, le monde Apple, le sport,
  la photo et tout un tas d'autres geekeries. Mes retours sur des produits et
  mes coups de gueules, tout ça dans la bonne humeur. Une partie du site est dédié
  à mon travail de développeur Web fullstack.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tfada.fr" # the base hostname & protocol for your site
amazon_url: "http://www.amazon.fr/?tag=tfadafr-21"

permalink: /:title.html
img: /images/
urlimg: http://tfada.fr/images/
default_tags: "apple,iphone,photos,sport,naturopathie,hightech"
rsslink: http://feeds.feedburner.com/tfada

# Build settings
markdown: kramdown

exclude: ["node_modules", "gulpfile.js", "package.json"]
future: false

collections:
  tweets:
    output: true
    permalink: /tweets/:path/

gems:
  - jekyll-sitemap